lib/src/supabase.dart
It is a bug fix.
Currently, when selecting the table in the builder with `.from(<table>)`, the `table` parameter won't be injected in the `url`. Instead, `"table"` will be injected as a string. This way, a table named `table` will be selected disregarding the passed parameter, usually causing an error, unless you have, indeed, a table named `table`.
The `table` parameter is passed correctly, fixing the aforementioned issue.
=> Fixed builder method not injecting `table` in the url

lib/supabase.dart
Exposing `RealtimeSubscription` so that you can declare variable of type `RealtimeSubscription` to later use it for unsubscribing. 
`RealtimeSubscription` is not exported, so cannot create variable of type `RealtimeSubscription`
`RealtimeSubscription` is exported, so you can create variable of type `RealtimeSubscription`
#4
=> Exposed 'RealtimeSubscription'

CHANGELOG.md, example/main.dart, lib/src/auth_user.dart, lib/src/supabase.dart, lib/src/supabase_query_builder.dart, lib/src/supabase_realtime_client.dart, lib/src/supabase_realtime_payload.dart, pubspec.yaml, test/client_test.dart
Migrates to null safety
Using null unsafe dart
Using null safe dart
Addresses #10
@phamhieu
=> Migrate to null-safety

lib/src/auth_session.dart, lib/supabase.dart
I noticed that `Provider` enum for auth was not being exported. I looked into it and decided to align the exports with [supabase-js](https://github.com/supabase/supabase-js/blob/master/src/index.ts) 
The exported members are not aligned with supabase-js
All exports should be aligned with supabase-js
=> Aligned exports with supabase-js

README.md
This PR aims to expand the `README` file to make it easier for new developers to get started with `supabase-dart`.
The examples are designed to be easy to understand for someone who just found the package. The explanations are simple and introduce only the most important API calls. The docs then link all the necessary references to dive deeper into the API for more complex usecases.
- I added a usage example for authentication and storage.
- I added a full section on how to implement authentications. (I still did not have the chance to try database and storage, I will make another PR when I learn more about them).
- I added a _What is Supabase_ section to introduce Supabase to someone who never heard of it and just found the package on pub.dev.
- I added a _Guides_ section similar to the …
=> Updated and expanded README docs

lib/supabase.dart
Improve developer experience by not having manually import realtime_client since it's a transitive dependency
Since RealtimeClient is a transitive dependency (for projects importing this package), dart doesn't automatically suggest importing from realtime_client package. So i added the one liner to supabase.dart
You need to manually import 'package:realtime_client/realtime_client.dart'
The manual import is not needed anymore.
-
=> Export realtime_client

.github/workflows/main.yml, analysis_options.yaml
This is just an idea that I thought might help the code to stay clean. Open to feedback on what everyone thinks! I can implement the same thing in all dart packages if this gets merged!
Adds a new action in the Github action workflow to check if the code is 
Github actions will make sure the line length is set to 80 characters per line. 
Currently Github actions does not check if the line length is set to 80 characters per line. 
@phamhieu 
I was thinking of adding another action that enforces all analyzer rules to pass with something like this:
```
- name: analyzer
run: dart analyze --fatal-warnings --fatal-infos .
```
but all the `print` statements gets caught. What do you think about adding the above action as well as disabling `avoid_print ` in the linter? With that, we can make sure …
=> Enforcing 80 characters per line with Github Actions

lib/src/supabase.dart
Changes the rpc params type definition from `Map<String, String>? params` to `Map<String, dynamic>? params`
It's not possible to send json (Map) data to a Stored Procedure.
It's possible to send any kind of data. Of course, instances of classes won't work. They need a `toJson()` method.
The underlying `PostgrestClient.rpc` method has the following type definition: `Map? params`.
It's serialized anyway [here](https://github.com/supabase/postgrest-dart/blob/master/lib/src/postgrest_builder.dart#L72).
I tested it with a `Map` and it worked.
=> fix: rpc params needed String as value

README.md, lib/src/supabase_stream_builder.dart
This PR fixes the bug where data is being added after StreamController has been closed. 
Related https://github.com/supabase/supabase-dart/issues/42
There is no check for whether StreamController is still open or not. 
Before adding data to StreamController, it will check if the controller is still open. 
I know we discussed removing `_streamController.close();`, but later noticed that removing that line might solve the bug, but that means the user is left with a streamController with no realtime update arriving as the realtime listener is removed at the same time.
=> fix: bug where data is added to stream after it is closed

CHANGELOG.md, lib/src/constants.dart, lib/src/supabase.dart, lib/src/version.dart, pubspec.yaml, test/client_test.dart
This PR adds `X-Client-Info` header to Supabase client. The header passed to Supabase client will override the headers of postgrest, gotrue, realtime, and storage clients. 
This PR contains:
- Code modifications to accept `headers` as a parameter of `SupabaseClient`
- Code modifications to pass the `headers` value to each client libraries
- Test code to make sure `X-Client-Info` header of each client libraries has been overridden
- Test code to make sure `X-Client-Info` header can be overridden by `supabase_flutter` library
- Bumped version to 0.2.6 so that this package can be released(by hand) once merged
Related https://github.com/supabase/supabase-dart/issues/45
`X-Client-Info` header cannot be set. 
`X-Client-Info` header will be set by default, and can be overridden by other …
=> chore: added X-Client-Info header

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
Updates `postgrest` to the newest version and publish version `0.2.7` of `supabase_dart`.
=> chore: publish version 0.2.7

lib/src/supabase_query_builder.dart, lib/src/supabase_realtime_client.dart
This PR adds `user_token` header to realtime channel subscription.
Related https://github.com/supabase/supabase-dart/issues/56
Related https://github.com/supabase/supabase-js/pull/270
Pass the user access token to Realtime in order to apply RLS on a per topic basis via WALRUS.
Not passing user_token to realtime channel subscription.
=> feat: add user_token when creating realtime channel subscription

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
Publish version 0.2.10, which includes the following changes:
- fix: type 'Null' is not a subtype of type 'List<dynamic>' in type cast
=> chore: publish version 0.2.10

lib/src/supabase.dart
Bug fix
You cannot call filter methods like `eq` on rpc queries.
Changed return type to `PostgrestFilterBuilder`. That's already the type of the underlying `rpc` method from `PostgrestClient`.
=> fix: use PostgrestFilterBuilder type for rpc

lib/src/supabase.dart
When logging out and back in with a different account, the changedAccessToken variable marked as late is not initialized.
Just changing it to a nullable variable fixes the issue.
=> Fixed changedAccessToken never initialized when changing account

.gitignore, CHANGELOG.md, lib/src/version.dart, pubspec.yaml
This updates gotrue_client to have the updated `signIn` with OpenID to help support native auth
Related:
https://github.com/supabase-community/gotrue-dart/pull/61
I then need to update https://github.com/supabase-community/supabase-flutter
=> chore: publish version 0.2.15

pubspec.yaml
Updated the `version` within pubspec.yaml, which I totally missed in [this PR](https://github.com/supabase-community/supabase-dart/pull/98).
=> fix: updated version in pubspec.yml to 0.2.15

CHANGELOG.md, lib/src/supabase_query_builder.dart, lib/src/supabase_stream_builder.dart, lib/src/version.dart, lib/supabase.dart, pubspec.yaml, test/mock_test.dart
It's helpful to specify the type when using subscriptions.
=> chore: 0.3.4+1 : Export type SupabaseRealtimePayload

lib/src/remove_subscription_result.dart, lib/src/supabase.dart, lib/src/supabase_realtime_error.dart, lib/supabase.dart, test/realtime_test.dart
remove inconsistency between supabase-js and supabase-dart client libraries on realtime remove functions.
breaking:
**removeAllSubscriptions** - returns list of removed subscriptions
**removeSubscription** - returns number of opened connections
@dshukertjr pls review PR, I don't know why, but I can't assign you as a reviewer.
=> refac: :recycle: refactoring of Realtime subscription remove functions

CHANGELOG.md, lib/src/version.dart, lib/supabase.dart, pubspec.yaml
Currently you need to explicitly import the storage package to its types.
This requires supabase-community/storage-dart/pull/37 to be merged.
=> fix: export storage types

CHANGELOG.md, README.md, lib/src/version.dart, pubspec.yaml, test/client_test.dart, test/mock_test.dart, test/realtime_test.dart
- fix: update storage to [v1.0.0-dev.3](https://github.com/supabase-community/storage-dart/blob/main/CHANGELOG.md#100-dev3)
- fix: add `web_socket_channel` to dev dependencies since it is used in tests
- fix: add basic `postgrest` test
=> chore: publish v1.0.0-dev.4

.github/workflows/main.yml, lib/src/supabase_stream_builder.dart, pubspec.yaml
I raised the min Dart version, to use type aliase. Postgrest already uses 2.16 so this doesn't change anything for devs.
Someone reported an issue on the [Discord](https://discord.com/channels/839993398554656828/869410418567831602/1018111988771070004) that you can't assign the stream to a typed variable. That's fixed by specifying the type on the extending `Stream`-
In addition, I fixed the typing on update call.
I don't have the time, but the stream method testing is weird. In normal run they pass, but in debug they don't.
=> fix: stream types

lib/src/supabase_client.dart
fixes https://github.com/supabase-community/supabase-flutter/issues/190
=> rpc: recreate a PostgresClient with proper auth headers

lib/src/supabase_client.dart, test/mock_test.dart
It wasn't possible to override the `apikey` and `Authorization` headers.
=> fix: custom headers

lib/src/supabase_stream_builder.dart, pubspec.yaml
Remove use of typedef on non-function types, which was introduced in 2.16
=> fix: lower the minimum required SDK to 2.12

README.md
Currently, it is unclear to Flutter developers whether they should use supabase or supabase_flutter package. This PR aims to clearly direct the Flutter devs to use supabase_flutter.
=> chore:  Update readme to direct Flutter developers to use supabase-flutter

lib/src/supabase_query_builder.dart, lib/src/supabase_stream_builder.dart, pubspec.yaml, test/mock_test.dart
Filters other than `eq` is not applied properly. There is a bug where everything becomes an `eq` filter. This PR fixes it.
```dart
supabase.from('table').stream(primaryKey: ['id']).lt('id', 10); // only retrieves rows where id is 10
```
This PR also contains the following:
- Fix the comment docs of `.stream()` to use v1.0 code
- Listening to the same stream more than once will emit the most recent data without going out to the server
=> fix: stream filter other than `eq` is not properly applied.

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
Would like to wait to include https://github.com/supabase-community/postgrest-dart/pull/94 and https://github.com/supabase-community/gotrue-dart/pull/105.
=> chore: publish v1.1.0

lib/src/supabase_client.dart, lib/src/supabase_query_builder.dart, lib/src/supabase_stream_builder.dart, test/mock_test.dart
Currently, when users listen to the same table multiple times, it creates the same realtime channel topic under the hood, which causes the stream to not return realtime data. This PR changes the topic to be the following format to make sure every stream creates a unique topic.
schema:table:incrementing_id
Related https://github.com/supabase/supabase-flutter/issues/231
=> fix: adds increment ID in channel topic inside `stream()`

lib/src/supabase_client.dart, pubspec.yaml
Adds retry option to Supabase client so that it can be passed onto storage client.
Related https://github.com/supabase/storage-dart/pull/44
=> feat: adds storage retry option

lib/src/supabase_stream_builder.dart, test/mock_test.dart
Related https://github.com/supabase/supabase-flutter/issues/319
Currently when using `.stream()`, the SDK throws if it receives an update or delete event for a record not in the in memory cache. However, situation like this could happen in a situation described in this issue https://github.com/supabase/supabase-flutter/issues/319
, or simply because the device was temporary offline, losing some events, and coming back online and receiving the delete or update events for the record that was missed, so throwing an error probably is not the ideal behavior. 
If an update event was received for record that does not exist in the cache, it will simply add the record and treat it like an insert. If an delete event of an record that does not exist was received, the SDK will just ignore it.
=> fix: handle update and delete on record that wasn't found properly

lib/src/realtime_client_options.dart, lib/src/realtime_params.dart, lib/src/supabase_client.dart, lib/supabase.dart
Realtime client has a [eventsPerSecond](https://github.com/supabase/realtime-dart/blob/main/lib/src/realtime_client.dart#L81) parameter, that can be overridden by passing it to the `params` parameter on the constructore of `RealtimeClient`. 
This PR adds a new `realtimeClientOptions` parameter of type `RealtimeClientOptions` to the `SupabaseClient` constructor and adds `eventsPerSecond` parameter.
I'm working on a realtime gaming app using Supabase and Flame, and with because of not being able to override `eventsPerSecond`, I can only send broadcast events 10 times a second, which makes the game feel not so smooth. Adding this option and bringing the eventsPerSecond up to 30 made it look very smoooth.
=> feat: realtimeClientOptions to SupabaseClient

CHANGELOG.md, lib/src/supabase_client.dart, lib/src/version.dart, pubspec.yaml
Reuses isolate for `rpc` call.
Fixes https://github.com/supabase/supabase-flutter/issues/353
=> fix: reuse isolate for `.rpc()` call

README.md
The checkboxes don't get displayed on [pub.dev](https://pub.dev/packages/supabase#status), which result in a weird list. I've changed it now, that only the current status is shown. I'm open to other ways. We could remove it entirely as well, since it's not in the supabase_flutter readme.
=> doc: fix status on readme

pubspec.yaml, test/mock_test.dart, test/realtime_test.dart
In order to be compatible with https://github.com/supabase/realtime-dart/pull/62, I had to fix the issue of depending on outdated version 2.2.0.
Adding another delay fixed [the issue](https://github.com/supabase/supabase-dart/pull/169#issuecomment-1381252913).
=> test: allow web_socket_channel 2.3.0

CHANGELOG.md, lib/src/supabase_client.dart, lib/src/version.dart, pubspec.yaml
Bug fix
Everytime calling `supabse.storage` you get a new `SupabaseStorageClient` instance, resulting in outdated auth headers after auth state change in `supabase.auth`.
Keeps one storage and functions client and update their authorization header.
close https://github.com/supabase/supabase-flutter/issues/376
=> fix: keep one storage and functions instance

lib/src/supabase_client.dart, pubspec.yaml
I noticed the `rest` variable is neither used nor set. I'm now using it to be able to set the headers correctly.
=> fix: keep one postgrest client

CHANGELOG.md, lib/src/supabase_client.dart, lib/src/version.dart, pubspec.yaml
Makes sure the headers is copied over in `from()` call.
Currently, if a user performs the following query, the second query fails, because the headers for the `single()` query remains. 
```dart
final singleRow = await supabase.from('random').select().limit(1).single();
final multipleRows = await supabase.from('random').select();
```
This PR fixes it by copying over the `rest.headers` on the `from()` call.
fixes https://github.com/supabase/supabase-flutter/issues/430
=> fix: copy headers value on from() call

lib/src/supabase_stream_builder.dart
Add support for the `in` filter to be used in `.stream()`. Same as the postgrest `in_` method, `in` is a reserved word in Dart, so had to change the filter from `in` to `in_`.
```dart
supabase.from('table').stream(primaryKey: ['id']).in_('name', ['Andy', 'Santiago', 'Holt']).listen();
```
=> feat: add in_ filter on stream()

CHANGELOG.md, lib/src/supabase_client.dart, lib/src/version.dart, pubspec.yaml
Currently, when user performs an query right after signing in, the query is performed with the session prior to signing in, resulting in empty query result. This PR fixes that.
```dart
await client.auth.signInWithPassword(email: email, password: password);
/// Unable to retrieve data if the data is protected with RLS
final data = await client
.from('profiles')
.select()
.eq('user_id', response.user?.id);
```
Fixes https://github.com/supabase/supabase-flutter/issues/456
=> fix: going back to using auth headers for SupabaseQueryBuilder

CHANGELOG.md, lib/src/supabase_client.dart, lib/src/version.dart, pubspec.yaml
This PR introduces a feature that allows for greater customization of HTTP headers in the Supabase Dart library.
Currently, the library uses a private _headers field to store HTTP headers for every request. Users can't modify these headers outside of the library code.
This PR adds a getter and setter for the _headers field, allowing users to customize headers for specific requests, such as adding or removing headers as needed.
This change will give users more control over the headers used in their requests, making the Supabase Dart library more flexible and adaptable to their needs. No relevant issues were identified. No screenshots are necessary as this is a code change.
Here's an example of how the new feature can be used in the RLS with the device_uid() function:
Suppose you have a …
=> make the headers property editable
