example/main.dart, lib/src/storage/fetch.dart, lib/src/storage/storage_bucket_api.dart, lib/src/storage/storage_file_api.dart, lib/src/storage/types.dart, lib/src/supabase.dart, lib/src/supabase_storage_client.dart, lib/supabase.dart, pubspec.yaml, test/storage_test.dart, test/test_env.dart
This is a first draft for the dart Storage API, with both the Bucket and the Files endpoints.
- I tried to keep the style & comment docs consistent with the the js implementation (https://github.com/supabase/supabase-js)
- I added some basic tests for each endpoint, but they require a working Supabase project (not ideal for tests), accessed using environment variables.
- More advanced testing will be required to make sure everything works fine (other file formats, cacheControl, error handling etc)
This is my first open source contribution, feedback will be much appreciated !
=> Implement Storage API

example/README.md
docs update
Since there are not many examples for supabase-dart, I have created a notes app with flutter and supabase.
=> added CRUD Example

README.md, example/main.dart
Hopefully it will guide people who first goes to pub.dev a little more guidance as to where to go for more info. 
Closes #35 
- No link to the documentation within README.md
- No realtime example
- Link towards the top of README.md as well as some comments about how developers should read the js doc. 
- realtime example on README.md
- insert, update, delete example on `example/main.dart`
=> Chore: Adding links and examples on README.md for better navigation for new comers 

README.md, example/main.dart, lib/src/supabase.dart, lib/src/supabase_query_builder.dart, lib/src/supabase_realtime_payload.dart, lib/src/supabase_stream_builder.dart, pubspec.yaml, test/mock_test.dart
Added a new method `stream()` to `SupabaseQueryBuilder`. The goal of `stream()` is to provide easier experience to work with realtime data. Internally, `stream()` will fetch the initial data using postgrest, and will listen to any updates following that. It will automatically handle updating data upon insert, update, or delete events from realtime. 
When users wanted to use the realtime feature, they had to first fetch the initial data manually, and then had to sync the data also manually with various realtime events. 
`stream()` takes care of fetching initial data as well as keeping the data sync with realtime events. 
For example, users can write something like this to implement a chat screen:
```dart
StreamBuilder<List<Map<String, dynamic>>>(
stream: supabase.from('chats').stream(), …
```
=> feat: Added stream() method to listen to realtime events with initial data. 

lib/src/supabase_query_builder.dart, lib/src/supabase_realtime_client.dart, lib/src/typedefs.dart, lib/supabase.dart
Feature
Closes #46 
Renamed Callback to SupabaseEventCallback
n/a
=> fix: expose supabase query builder

.github/workflows/main.yml, lib/src/auth_session.dart, lib/src/auth_user.dart, lib/src/supabase.dart, lib/src/supabase_query_builder.dart, lib/src/supabase_realtime_client.dart, lib/src/supabase_stream_builder.dart, lib/supabase.dart, test/mock_test.dart
The [Github action we used to use for Dart language](https://github.com/cedx/setup-dart) is now deprecated, and there is a [one published by the official dart language team](https://github.com/marketplace/actions/setup-dart-sdk), so using that one instead of the current one. 
This PR will include any analysis error fix that is raised with the newest stable dart language `2.14.0`. 
Using a deprecated Github Action.
Using Github Action published by the official dart lang team and also testing stable, beta, dev version of dart language.
=> chore: updated Github action to use official dart-lang action to setup dart

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
Publish version 0.2.9, which includes the following changes:
- feat: add user_token when creating realtime channel subscription
- fix: typo on Realtime data as Stream on readme.md
=> chore: publish version 0.2.9

lib/src/supabase.dart, lib/src/supabase_query_builder.dart, lib/src/supabase_realtime_client.dart, lib/src/supabase_realtime_payload.dart, lib/src/supabase_stream_builder.dart, test/mock_test.dart
Sorry needed a new pr, because I accidentally chose my main branch. See #75 for details.
=> docs: correct stream method documentation

README.md
Related https://github.com/supabase-community/supabase-dart/pull/82
=> chore: Updated stream example in readme to reflect most recent change

.github/workflows/main.yml
Fixes a bug where github actions don't execute properly
Related https://github.com/dart-lang/setup-dart/issues/46#issuecomment-1040022923
=> fix: github actions not running properly

CHANGELOG.md, lib/src/supabase_query_builder.dart, lib/src/version.dart, pubspec.yaml
Updates gotrue and publishes v0.2.16
=> chore: publish 0.3.0

CHANGELOG.md, lib/src/supabase.dart, lib/src/version.dart, pubspec.yaml
Implemented functions support so that users can invoke Supabase functions from within their app. 
JS SDK implementations:
https://github.com/supabase/supabase-js/blob/master/src/SupabaseClient.ts
=> feat: add functions support

lib/src/version.dart, lib/supabase.dart, pubspec.yaml
1. Export what is being exported within functions_client
1. Update the version to 0.3.1+1
=> fix: exporting classes inside functions_client

lib/src/supabase_query_builder.dart, test/mock_test.dart
fixes https://github.com/supabase-community/supabase-flutter/issues/81
=> fix: Calling postgrest endpoints within realtime callback throws exception

test/mock_test.dart
Wanted to add some tests after seeing this issue, but the actual issue itself seemed be resolved. Anyway, it's nice to have more coverage. 
https://github.com/supabase-community/supabase-flutter/issues/215
=> chore: added tests for listening to update delete in stream

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
Wanted to ship this update as it includes a fix that could be critical to some people.
=> chore: publish v1.0.0-dev.9

lib/src/supabase_query_builder.dart, lib/src/supabase_stream_builder.dart, test/mock_test.dart
I've updated the StreamBuilder to be able to be listened again after subscription cancel.
=> test: listen, cancel and listen again

CHANGELOG.md, lib/src/supabase_query_builder.dart, lib/src/supabase_stream_builder.dart, lib/src/version.dart, pubspec.yaml, test/mock_test.dart
Also included the primary key breaking change discussed [here](https://github.com/supabase-community/supabase-flutter/issues/218#issuecomment-1279038003).
```dart
// Old
supabase.from('table').stream(['id']);
// New
supabase.from('table').stream(primaryKey: ['id']);
```
=> chore: publish v1.0.0 🚀

example/main.dart
`example/main.dart` was commented out previously. This PR adds a proper example back.
=> fix: update the commented out examples

lib/src/supabase_stream_builder.dart, test/mock_test.dart
The `isBroadcast` getter weren't set and the methods didn't use a `BehaviourSubject`.
close https://github.com/supabase/supabase-flutter/issues/258
=> fix: implement asyncMap and asyncExpand

lib/src/supabase_client.dart
close supabase/supabase-flutter#235
=> fix: add missing options parameter to rpc

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
I looked into automatic package release, but it seems like it doesn't really reduce any process during package release unless we can automatically publish Github Release via Github Actions, so will just release this one manually. Still looking into how we might be able to better automate the release process.
=> chore: publish v1.5.0

CHANGELOG.md, lib/src/supabase_client.dart, lib/src/version.dart, pubspec.yaml
- Adds `authFlowType` parameter and asyncStorage to support pkce flow.
To be merged and released after https://github.com/supabase/gotrue-dart/pull/135
=> feat: add async storage as parameter to support pkce flow
